[mongodb]
mongodb-dev.asadaws2026.online

[catalogue]
catalogue-dev.asadaws2026.online

[redis]
redis-dev.asadaws2026.online

[user]
user-dev.asadaws2026.online

[cart]
cart-dev.asadaws2026.online

[mysql]
mysql-dev.asadaws2026.online

[shipping]
shipping-dev.asadaws2026.online

[rabbitmq]
rabbitmq-dev.asadaws2026.online

[payment]
payment-dev.asadaws2026.online

[frontend]
frontend-dev.asadaws2026.online
ansible_python_interpreter: /usr/bin/python3.9

[all:vars]
ansible_user=ec2-user 
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.asadaws2026.online
CATALOGUE_HOST=catalogue-dev.asadaws2026.online
REDIS_HOST=redis-dev.asadaws2026.online
USER_HOST=user-dev.asadaws2026.online
CART_HOST=cart-dev.asadaws2026.online
MYSQL_HOST=mysql-dev.asadaws2026.online
SHIPPING_HOST=shipping-dev.asadaws2026.online
RABBITMQ_HOST=rabbitmq-dev.asadaws2026.online
PAYMENT_HOST=payment-dev.asadaws2026.online

