- name: configure user
  become: yes
  hosts: user
  tasks:
  - name: enale nodejs 20
    # ansible.builtin.command: dnf module enable nodejs:20 -y
    ansible.builtin.dnf:
    name: '@nodejs:20'
    state: present

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: creating system user roboshop
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "Roboshop system user"
   
  - name: delete app directory
    ansible.builtin.file:
      path: /app
      state: absent
  
  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: delete user zip file
    ansible.builtin.file:
      path: /tmp/user.zip
      state: absent
  
  - name: download user
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip

  - name: unarchive user
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    community.general.npm:
      path: /app

  - name: copy the user service
    ansible.builtin.template:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: systemd deamon reload to reread configs 
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: enable and start the service
    ansible.builtin.service:
      name: user
      state: restarted
      enabled: yes